<?php

namespace LimeTrail\Bundle\Builders;

use Doctrine\ORM\EntityManager;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Translation\TranslatorInterface;
use Symfony\Component\Routing\RouterInterface;
use Thrace\DataGridBundle\DataGrid\DataGridFactoryInterface;
use Thrace\DataGridBundle\DataGrid\CustomButton;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoresByClientBuilder
{
    const IDENTIFIER = 'stores_by_client';
    protected $factory;
    protected $translator;
    protected $router;
    protected $em;
    protected $container;

    public function __construct(DataGridFactoryInterface $factory,
             TranslatorInterface $translator,
             RouterInterface $router,
             EntityManager $em,
             ContainerInterface $container)
    {
        $this->factory = $factory;
        $this->translator = $translator;
        $this->router = $router;
        $this->em = $em;
        $this->container = $container;
    }

    public function build()
    { /* https://github.com/thrace-project/datagrid-bundle/blob/master/Resources/doc/index.md#installation
    http://stackoverflow.com/questions/7413905/jqgrid-populate-select-control-on-row-edit

    */

        $query = 'pc.id, p.projectNumber,
                  p.canonicalName as ProjectName, pt.name as ProjectType,
                  dt.name as DevelopmentType, proto.name as Prototype,
                  p.sap as SapNumber, ps.name as Status,
                  j.jobRole, c.firstName, c.middleName, c.lastName, c.jobTitle, c.directPhone,
                  c.mobilePhone, pc';

        $gridModeler = $this->container->get('lime_trail_grid_model.provider');
        $gridModeler->createModel($query);

        $dataGrid = $this->factory->createDataGrid(self::IDENTIFIER);
        $dataGrid
            ->setQueryBuilder($this->getQueryBuilder($query))
            ->setCaption($this->translator->trans('Stores by Client'))
            ->setColNames($gridModeler->getColNames())
            ->setColModel($gridModeler->getColModel())

            ->enableSearchButton(true)
            ->enableAddButton(false)
            ->enableEditButton(true)
            ->enableDeleteButton(false)
            ->setSortName('c.lastName')
            ->setSortOrder('ASC')
            ->setShrinkToFit(false)
            ->setHeight('100%')
            ->setRowNum(50)
            //->setDependentDataGrids(array('projects_contact'))
        ;

        $dataGrid->addCustomButton(new CustomButton('ExportXls', array(
            'title' => 'Export to Xls',
            'caption' => 'Export',
            'buttonIcon' => 'ui-icon-document',
            'position' => 'last',
            'uri' => $this->router->generate('limetrail_storeinformation_exportgrid',
                      array('grid' => self::IDENTIFIER)
                      ),
            )
          )
        );

        return $dataGrid;
    }

    protected function getQueryBuilder($query)
    {
        $qb = $this->em->getRepository('LimeTrailBundle:ProjectContacts')->createQueryBuilder('pc');

        $qb->select($query)
            ->Join('pc.contact', 'c')
            ->Join('pc.project', 'p')
            ->Join('pc.jobrole', 'j')
            ->leftJoin('p.ProjectType', 'pt')
            ->leftJoin('p.DevelopmentType', 'dt')
            ->leftJoin('p.DescriptionOfType', 'des')
            ->leftJoin('p.ProgramYear', 'py')
            ->leftJoin('p.Prototype', 'proto')
            ->leftJoin('p.ProjectStatus', 'ps')
            ->Join('p.dates', 'd')
        ;

        return $qb;
    }
}
