<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function findByName($name)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c FROM LimeTrailBundle:Company c
      WHERE c.name = :n'
    )
    ->setParameters(array(
      'n' => $name,
    ));

        return $q->getOneOrNullResult();
    }

    public function findByAddress($companyName, $address)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c, o, a FROM LimeTrailBundle:Company c
      LEFT JOIN c.offices o
      LEFT JOIN o.address a
      WHERE c.name = :n
      AND a.address = :a'
    )
    ->setParameters(array(
      'n' => $companyName,
      'a' => $address,
    ));

        return $q->getSingleResult();
    }

    public function getCompanyByPartialName($partial)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c FROM LimeTrailBundle:Company c
      WHERE c.name LIKE :p'
      )
      ->setParameter('p', $partial.'%');

        return $q->getResult();
    }
}
