<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findByFullName($firstname, $middlename, $lastname)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c FROM LimeTrailBundle:Contact c
      WHERE c.firstName = :fn AND c.lastName = :ln AND c.middleName = :mn'
    )
    ->setParameters(array(
      'fn' => $firstname,
      'mn' => $middlename,
      'ln' => $lastname,
    ));

        return $q->getSingleResult();
    }

    public function findByShortNameAndDomain($firstname, $lastname, $domain)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c FROM LimeTrailBundle:Contact c
      WHERE c.firstName = :fn AND c.lastName = :ln AND c.email LIKE :mn'
    )
    ->setParameters(array(
      'fn' => $firstname,
      'mn' => $domain,
      'ln' => $lastname,
    ));

        return $q->getSingleResult();
    }

    public function findByCompanyId($id)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c, comp FROM LimeTrailBundle:Contact c
      JOIN LimeTrailBundle:Company comp
      WHERE comp.id = :id'
    )
    ->setParameters(array(
      'id' => $id,
    ));

        return $q->getOneResult();
    }

    public function findByCompany($name)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT c FROM LimeTrailBundle:Contact c
      JOIN c.office o
      JOIN o.company comp
      WHERE comp.name = :n'
    )
    ->setParameters(array(
      'n' => $name,
    ));

        return $q->getResult();
    }
}
