<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends EntityRepository
{
    public function findByAddress($address)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT o FROM LimeTrailBundle:Office o
      WHERE o.name = :a'
    )
    ->setParameters(array(
      'a' => $address,
    ));

        return $q->getSingleResult();
    }
}
