<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectContactsRepository extends EntityRepository
{
    public function findByProjectAndContact($project, $contact)
    {
        $projectId = $project->getId();

        $contactId = $contact->getId();

        $q = $this->getEntityManager()->createQuery(
      'SELECT pc FROM LimeTrailBundle:ProjectContacts pc
      JOIN pc.project p
      JOIN pc.contact c
      WHERE p.id = :p AND c.id = :c'
    )
    ->setParameters(array(
      'p' => $projectId,
      'c' => $contactId,
    ));

        return $q->getOneOrNullResult();
    }

    public function findAllByJobRole($project, $jobrole)
    {
        $projectId = $project->getId();

        $jobroleId = $jobrole->getId();

        $q = $this->getEntityManager()->createQuery(
      'SELECT pc FROM LimeTrailBundle:ProjectContacts pc
      JOIN pc.project p
      JOIN pc.jobrole j
      WHERE j.id = :j
        AND p.id = :p'
    )->setParameters(array(
      'j' => $jobroleId,
      'p' => $projectId,
    ));

        return $q->getResult();
    }
}
