<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectChangeRepository extends EntityRepository
{
  public function findByProjectIdAndChangeId($projectId, $changeId)
  {
    $q = $this->getEntityManager()->createQuery(
      'SELECT pc FROM LimeTrailBundle:ProjectChangeInitiation pc
        JOIN pc.project p
        JOIN pc.change c
        WHERE
          p.id = :project
          AND c.id = :change'
    )
    ->setParameters(array(
      'project' => $projectId,
      'change' => $changeId,
    ));
    
    return $q->getResult();
  }
}
