<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectinformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectDatesRepository extends EntityRepository
{
  public function getRundates()
  {
qb = $this->createQueryBuilder('p');

        $qb->select('p.runDate');

    return $qb->getQuery()->getResult();
  }
}
