<?php

namespace LimeTrail\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoreInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreInformationRepository extends EntityRepository
{
    public function findByNumberAndSequence($number, $sequence)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT s,p FROM LimeTrailBundle:StoreInformation s
      JOIN s.projects p
      WHERE s.storeNumber = :str AND p.Sequence = :seq'
    )
    ->setParameters(array(
      'str' => $number,
      'seq' => $sequence,
    ));

        return $q->getOneOrNullResult();
    }

    public function findByProjectId($id)
    {
        $q = $this->getEntityManager()->createQuery(
      'SELECT s FROM LimeTrailBundle:StoreInformation s
      JOIN s.projects p
      WHERE p.id = :id'
    )->setParameter('id', $id);

        return $q->getOneOrNullResult();
    }
}
