<?php

namespace Rha\ProjectManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StoreInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeReviewRepository extends EntityRepository
{
}
